### ISSUE TITLE
Codec error when installing

### ISSUE THREAD

**Issue by yoavram** [mattja/sdeint#2]
```
 pip install sdeint
Collecting sdeint
  Downloading sdeint-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\yoavram\AppData\Local\Temp\pip-build-ptlgr1og\sdeint\setup.py", line 48, in <module>
        long_description=read('README.rst'),
      File "C:\Users\yoavram\AppData\Local\Temp\pip-build-ptlgr1og\sdeint\setup.py", line 11, in read
        return codecs.open(os.path.join(here, *parts), 'r').read()
      File "D:\Anaconda3\lib\encodings\cp1255.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9f in position 1592: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\yoavram\AppData\Local\Temp\pip-build-ptlgr1og\sdeint
```
Same thing happens when installing directly from the code downloaded from github.

Python 3.4, Windows 7 64-bit.

**Comment by yoavram** [comment]
Hi it seems that the PR wasn't updates on PyPI.

**Comment by mattja** [comment]
Thanks for your reminder.  I have just updated PyPi with version 0.2.1.

**Comment by yoavram** [comment]
Great, thanks!
